spring.application.name=vinicius_reis_zimmermann-trabalho-java

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=${SERVER_PORT:8080}

app.runner.enabled=false

app.viacep.url=https://viacep.com.br/ws
spring.cloud.openfeign.client.config.viaCepClient.connectTimeout=3000
spring.cloud.openfeign.client.config.viaCepClient.readTimeout=5000

entrega.service.url=${ENTREGA_SERVICE_URL:http://localhost:8081}
spring.cloud.openfeign.client.config.entrega-service.connectTimeout=${ENTREGA_CONNECT_TIMEOUT:2000}
spring.cloud.openfeign.client.config.entrega-service.readTimeout=${ENTREGA_READ_TIMEOUT:3000}
