spring.application.name=vinicius_reis_zimmermann-trabalho-java

spring.datasource.url=jdbc:h2:mem:vinicius_reis_zimmermann
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.runner.enabled=false

app.viacep.url=https://viacep.com.br/ws
spring.cloud.openfeign.client.config.viaCepClient.connectTimeout=3000
spring.cloud.openfeign.client.config.viaCepClient.readTimeout=5000

entrega.service.url=http://localhost:8081
spring.cloud.openfeign.client.config.entrega-service.connectTimeout = 2000
spring.cloud.openfeign.client.config.entrega-service.readTimeout = 3000